thermos/models.py
from datetime import datetime
from sqlalchemy import desc
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from . import stats_client
from . import db

tags = db.Table('bookmark_tag',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
    db.Column('bookmark_id', db.Integer, db.ForeignKey('bookmark.id'))
)


class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.String(300))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)
    _tags = db.relationship('Tag', secondary=tags, lazy='joined',
                            backref=db.backref('bookmarks', lazy='dynamic'))

    def __init__(self, **kwargs):
        super(Bookmark, self).__init__(**kwargs)
        stats_client.incr('thermos.models,type=bookmark')                   #increment the bookmark counter

    @staticmethod
    def newest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)

    @property
    def tags(self):
        return ",".join([t.name for t in self._tags])

    @tags.setter
    def tags(self, string):
        if string:
            self._tags = [Tag.get_or_create(name) for name in string.split(',')]
        else:
            self._tags = []

    def __repr__(self):
        return "<Bookmark '{}': '{}'>".format(self.description, self.url)


class User(db.Model, UserMixin):
    #^UserMixin from flask_login exposes methods to determine auth state
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')
    password_hash = db.Column(db.String(80))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        stats_client.incr('thermos.models,type=user')                       #increment the user counter

    @property
    def password(self):
        raise AttributeError('password: write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()

    def __repr__(self):
        return '<User %r>' % self.username


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    def __init__(self, **kwargs):
        super(Tag, self).__init__(**kwargs)
        stats_client.incr('thermos.models,type=tag')                       #increment the tag counter

    @staticmethod
    def get_or_create(name):
        name = name.strip()
        try:
            return Tag.query.filter_by(name=name).one()
        except:
            return Tag(name=name)

    @staticmethod
    def all():
        return Tag.query.all()

    def __repr__(self):
        return self.name

class Bookmark_flag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    value = db.Column(db.Integer, nullable=False, unique=True)

    def __init__(self, **kwargs):
        super(Bookmark_flag, self).__init__(**kwargs)
        stats_client.incr('thermos.models,type=bookmark_flag')              #increment the bookmark_flag counter

    @staticmethod
    def find_next(count=1):
        def isp(nbr):
            for i in range(2,nbr-1):
                if nbr%i == 0:
                    return False
            return True

        last_result = db.session.query(db.func.max(Bookmark_flag.value)).first()
        nbr=last_result[0]
        print "last nbr is:{}".format(nbr)
        while count >= 0:
            while True:
                nbr += 1
                if isp(nbr):
                    db.session.add(Bookmark_flag(value=nbr))
                    count -= 1
                    found=nbr
                    break
        db.session.commit()
        return found

    def __repr__(self):
        return self.value

thermos/bookmarks/forms.py
from flask_wtf import Form
from wtforms.fields import StringField
from flask_wtf.html5 import URLField
from wtforms.validators import DataRequired, Regexp, url, ValidationError


# form object for the bookmark views (shared among all)
class BookmarkForm(Form):
    url = URLField('The URL of your bookmark:', validators=[DataRequired(), url()])
    description = StringField('Add an optional description:')
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$',
                  message="Tags can only contain letters and numbers")])

    def validate(self):
        if not self.url.data.startswith("http://") or \
            self.url.data.startswith("https://"):
                self.url.data = "http://" + self.url.data

        if not Form.validate(self):
            return False

        if not self.description.data:
            self.description.data = self.url.data

        #filter out empty and duplicate tag names
        stripped = [t.strip() for t in self.tags.data.split(',')] #split string on comma, strip whitespace
        not_empty = [tag for tag in stripped if tag] #filter out blanks
        tagset = set(not_empty) #put remaining items in a set, which inherently deduplicates
        self.tags.data=','.join(tagset) #join back into a csv string

        return True

thermos/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, BooleanField, SubmitField
from flask_wtf.html5 import URLField
from wtforms.validators import DataRequired, url, Length, Email, Regexp, EqualTo,\
    url, ValidationError

from models import User

thermos/__init__.py
import os

from flask import Flask, request #, render_template, request, redirect, url_for, flash
from flask_sqlalchemy import SQLAlchemy, get_debug_queries
from flask_login import LoginManager
from flask_moment import Moment
from flask_debugtoolbar import DebugToolbarExtension
from flask_metrics import statsd_middleware, StatsClient, Annotator

from .config import config_by_name

db = SQLAlchemy()                                   # create instance of SQLAlchemy ORM engine
stats_client = StatsClient()                        # create instance of our app level statsd client
annotator = Annotator()

#Configure Authentication
login_manager=LoginManager()                        # begin to configure authentication
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"             # set where to send people needing to log in


toolbar = DebugToolbarExtension()                   # enable the debug toolbar (found on right when debug=true)
moment = Moment()                                   # framework taking timestamps and converting to '2 hours ago'


def create_app(config_name):                        # app factory, generating our application object
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    toolbar.init_app(app)

    stats_client.init_app(app)                      # initialize our statsd client, assign it within app
    annotator.init_app(app)                         # initialize our annotator, assign it within app
    app.wsgi_app = statsd_middleware(app)           # initialize our statsd middleware
    # annotator.write(module='app',action='startup',text='application initialized')

    from .main import main as main_blueprint        # blueprints are self contained portions of an application
    app.register_blueprint(main_blueprint, url_prefix='/')

    from .bookmarks import bookmarks as bkm_blueprint
    app.register_blueprint(bkm_blueprint, url_prefix='/bookmarks')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

thermos/bookmarks/__init__.py
from flask import Blueprint
bookmarks = Blueprint('bookmarks',__name__)

from . import views

thermos/bookmarks/views.py
# imports for web framework
from flask import render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, login_user, logout_user, current_user

#imports from other parts of the application
from . import bookmarks
from .forms import BookmarkForm
from .. import db
from .. import stats_client
from ..models import User, Bookmark, Tag, Bookmark_flag

#add bookmark
@bookmarks.route('/add', methods=['GET','POST'])
@login_required
def add():
    form = BookmarkForm()
    if form.validate_on_submit():
        url = form.url.data
        description = form.description.data
        tags = form.tags.data
        bm = Bookmark(user=current_user, url=url, description=description, tags=tags)
        db.session.add(bm)
        db.session.commit()
        # app.logger.debug("Stored Bookmark: '{}'".format(url))
        flash("Stored Bookmark: '{}'".format(url))
        stats_client.incr('thermos.bookmarks,operation=add')
        return redirect(url_for('main.index'))

    return render_template('bookmark_form.html',form=form, title="Add a bookmark")

#edit bookmark
@bookmarks.route('/edit/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def edit_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    form = BookmarkForm(obj=bookmark) #data submitted on user request takes precident over data from database
    if form.validate_on_submit():
        form.populate_obj(bookmark)
        db.session.commit()
        flash("Stored '{}'".format(bookmark.description))
        stats_client.incr('thermos.bookmarks,operation=edit')
        return redirect(url_for('.user',username=current_user.username))
    return render_template('bookmark_form.html', form=form, title="Edit bookmark")

#delete bookmark
@bookmarks.route('/delete/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def delete_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    if request.method == "POST":
        db.session.delete(bookmark)
        db.session.commit()
        flash("Deleted '{}'".format(bookmark.description))
        stats_client.incr('thermos.bookmarks,operation=delete')
        return redirect(url_for('.user', username=current_user.username))
    else:
        flash("Please confirm deleting the bookmark.")
    return render_template('confirm_delete.html', bookmark=bookmark, nolinks=True)

#display a users bookmarks
@bookmarks.route('/user/<username>')
def user(username):
    user= User.query.filter_by(username=username).first_or_404()
    return render_template('user.html',user=user)

#display list of bookmarks with a tag
@bookmarks.route('/tag/<name>')
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('tag.html', tag=tag)

@bookmarks.route('/bookmark_flag', methods=['GET'])
def primes():
    count = request.args.get('count')
    print type(count)
    if not count:
        count = 1
    return render_template('primes.html', nbr=Bookmark_flag.find_next(int(count)))

thermos/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

thermos/main/views.py
from flask import render_template, request
from . import main
from .. import login_manager
from ..models import User, Bookmark, Tag, Bookmark_flag


@login_manager.user_loader
#^tells flask-login how to retrieve a user by id
def load_user(userid):
    return User.query.get(int(userid))

#main page
@main.route('/')
# @main.route('/index')
def index():
    # with statsd_client.timer('index'):
        return render_template('index.html', new_bookmarks=Bookmark.newest(5))

# unauthorized page
@main.app_errorhandler(403)
def page_not_found(e):
    return render_template("403.html"),403

# page not found
@main.app_errorhandler(404)
def page_not_found(e):
    return render_template("404.html"),404

# server error
@main.app_errorhandler(500)
def server_error(e):
    return render_template("500.html"),500

# get list of all tags
@main.app_context_processor
def inject_tags():
    return dict(all_tags=Tag.all)

thermos/views.py
from flask import Flask, render_template, request, redirect, url_for, flash, abort
#from flask_login import login_required, current_user

from models import Bookmark, User, Tag
from thermos import db, app, login_manager



# @app.route('/login', methods=['GET','POST'])
# def login():
#     form = LoginForm()
#     if form.validate_on_submit():
#         #login and validate user
#         user = User.get_by_username(username=form.username.data)
#         if user is not None and user.check_password(form.password.data):
#             login_user(user, form.remember_me.data)
#             flash('logged in successfully as {}.'.format(user.username))
#             return redirect(request.args.get('next') or url_for('index'))
#             #^'next' will redirect the user to where they were attempting to go.  (look at browser query string)
#         flash('Incorrect username or password.')
#     return render_template('login.html', form=form)


# @app.route('/logout')
# def logout():
#     logout_user()
#     return redirect(url_for('index'))
#
#
# @app.route('/signup', methods=['GET','POST'])
# def signup():
#     form = SignupForm()
#     if form.validate_on_submit():
#         user = User(email=form.email.data,
#                     username=form.username.data,
#                     password=form.password.data)
#         db.session.add(user)
#         db.session.commit()
#         flash('Welcome, {}! Please login to continue.'.format(user.username))
#         return redirect(url_for('login'))
#     return render_template('signup.html', form=form)
#

thermos/templates/add.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- Add URL
{% endblock %}

{% block content %}

        <section>
        <h1>Add a new URL</h1>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <table>
                    {{ render_field(form.url, size=50) }}
                    {{ render_field(form.description, size=50) }}

                    <tr>
                        <td></td>
                        <td><button type="submit">Submit</button></td>
                    </tr>
                </table>
            </form>
        </section>

{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/base.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %} </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href=" {{ url_for('static', filename='css/normalize.min.css') }} ">
        <link rel="stylesheet" href=" {{ url_for('static', filename='css/main.css') }} ">

        <!--<script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>-->
    </head>
    <body>

        <div class="header-container">
            <header class="wrapper clearfix">
                <a href="{{url_for('main.index') }}" ><h1 class="title">THERMOS</h1></a>
                <nav>
                    <ul>
                        <li><a href=" {{ url_for('bookmarks.add') }} ">Add URL</a></li>
                        {% if current_user.is_authenticated %}
                            <li><a href="{{url_for('bookmarks.user', username=current_user.username) }}">My Links</a></li>
                            <li><a href="{{url_for('auth.logout') }}">Sign out</a></li>
                        {% else %}
                            <li><a href="{{url_for('auth.signup') }}">Sign up</a></li>
                            <li><a href="{{url_for('auth.login') }}">Sign in</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">
                <article class=flashes>
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                            <li> {{ message }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% endwith %}
                </article>
                {% block content %}
                {% endblock %}

                {% block sidebar %}
                    <aside>
                        <h3>Tags</h3>
                            {% for t in all_tags() %}
                                <a href="{{ url_for('bookmarks.tag',name=t)}}">{{ t }}</a>
                            {% endfor %}
                    </aside>
                {% endblock %}
            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <h3>Social Bookmarking at it's simplest. <i>by Butterman Industries</i></h3>
            </footer>
        </div>

        <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>-->
        <!--<script>window.jQuery || document.write('<script src=" {{ url_for('static', filename='js/vendor/jquery-1.11.2.min.js') }} "><\/script>')</script>-->
        <!--<script src="js/main.js"></script>-->

        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}

    </body>
</html>

thermos/templates/bookmark.html
<div class="bookmark">
    <a class="header" href="{{bookmark.url }}">
       <h3 class="description">
           {{bookmark.description|truncate(50, killwords=True) }}
       </h3>
        <span class="url">
            {{bookmark.url|truncate(50, killwords=True) }}
        </span>
    </a>

    <div class="info">
        <span class="tags">
            {% if bookmark.tags %}
                {% for t in bookmark._tags %}
                    <a href="{{url_for('bookmarks.tag',name=t) }}"> {{ t }}</a>
                {% endfor %}
            {% endif %}
        </span>

        <br>

        Added by <a href="{{url_for('bookmarks.user',username=bookmark.user.username)}}">
            {{ bookmark.user.username }}
        </a>
        {{ moment(bookmark.date).fromNow() }}.
        {% if current_user == bookmark.user %}
            <span class="editlinks">
                <a href="{{ url_for('bookmarks.edit_bookmark', bookmark_id=bookmark.id) }}">edit</a>
                <a href="{{ url_for('bookmarks.delete_bookmark', bookmark_id=bookmark.id) }}">delete</a>
            </span>
        {% endif %}
    </div>
</div>

thermos/templates/bookmark_form.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- {{ title }}
{% endblock %}

{% block content %}

        <section>
        <h1>{{ title }}</h1>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <table>
                    {{ render_field(form.url, size=50) }}
                    {{ render_field(form.description, size=50) }}
                    {{ render_field(form.tags, size=50) }}
                    <tr class="submit">
                        <td></td>
                        <td><button type="submit">Submit</button></td>
                    </tr>
                </table>
            </form>
        </section>

{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/bookmark_list.html
<ul class="bookmarks" >
    {% for bookmark in bookmarks %}
        {% include "bookmark.html" %}
    {% endfor %}
</ul>

thermos/templates/confirm_delete.html
{% extends "base.html" %}

{% block title %}
Thermos -- Delete bookmark
{% endblock %}

{% block content %}
    <section>
        <h1 style="clear:both">Confirm Delete</h1>

        {% include "bookmark.html" %}

        <form action"" method="post">
            <span style="color:red" >Are you sure you want to delete this bookmark?</span>
            <br><br>
            <a href="{{url_for('bookmarks.user', username=current_user.username) }}">
                <button type="button">No, take me out of here</button>
            </a>
            <button type="submit">Yes, delete it</button>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/form_macros.html
{% macro render_field(field) %}
    <tr> {% if field.errors %} class="error" {% endif %} </tr>
        <td> {{ field.label }} </td>
        <td> {{ field(**kwargs)|safe }} </td>
    </tr>
    <tr class="error">
        <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
{% endmacro %}

thermos/templates/index.html
{% extends "base.html" %}

{% block title %}
Thermos -- Welcome
{% endblock %}

{% block content %}
    <article>
        <header>
            <h1>Welcome</h1>
            <p>Here's where I tell you how cool the site is.  In reality, it's all the bookmarks you'll never need.</p>
        </header>
        <section>
            <h2>Recent Added Bookmarks</h2>
            <!--{% if new_bookmarks %}-->
                <!--<ul>-->

                    <!--{% for bm in new_bookmarks: %}-->
                        <!--<li><a href="{{ url_for('bookmarks.user', username=bm.user.username)}}">{{ bm.user.username }}</a> added <a href="{{ bm.url }}">{{ bm.description }}</a></li>-->
                    <!--{% endfor %}-->
                <!--</ul>-->
            <!--{% else %}-->
                <!--No bookmarks added yet.-->
            <!--{% endif %}-->
            {% if new_bookmarks.count() > 0 %}
                {% with bookmarks=new_bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                No bookmarks added yet.
            {% endif %}
        </section>
        <!--<section>-->
            <!--<h3>section2</h3>-->
            <!--<p>stuff</p>-->
        <!--</section>-->
    </article>
{% endblock %}

thermos/templates/index2.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="../static/css/normalize.min.css">
        <link rel="stylesheet" href="../static/css/main.css">

        <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>
    <body>

        <div class="header-container">
            <header class="wrapper clearfix">
                <h1 class="title">h1.title</h1>
                <nav>
                    <ul>
                        <li><a href=" {{ url_for('add') }} ">Add URL</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Sign in</a></li>
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">

                <article>
                    <header>
                        <h1>article header h1</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec.</p>
                    </header>
                    <section>
                        <h2>Title: {{ title }}</h2>
                        <p>Text: {{ text[1] }}</p>
                        <p>{{ user }}</p>
                        <p>{{ user.initials() }}</p>
                    </section>
                    <section>
                        <h2>article section h2</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor. Etiam ullamcorper lorem dapibus velit suscipit ultrices. Proin in est sed erat facilisis pharetra.</p>
                    </section>
                    <footer>
                        <h3>article footer h3</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor.</p>
                    </footer>
                </article>

                <aside>
                    <h3>aside</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor. Etiam ullamcorper lorem dapibus velit suscipit ultrices.</p>
                </aside>

            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <h3>footer</h3>
            </footer>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="js/main.js"></script>
    </body>
</html>

thermos/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- Login
{% endblock %}

{% block content %}

        <section>
        <h1 style="clear:both">Please Login</h1>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <table>
                    {{ render_field(form.username, size=50) }}
                    {{ render_field(form.password, size=50) }}
                    {{ render_field(form.remember_me) }}
                    {{ render_field(form.submit) }}
                </table>
            </form>
        </section>

{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/primes.html
{% extends "base.html" %}

{% block title %}
Thermos -- Welcome
{% endblock %}

{% block content %}
    <article>
        <header>
            <h1>calculates primes</h1>
        </header>
        <section>
            <h2>{{ nbr }}</h2>
        </section>
    </article>
{% endblock %}

thermos/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- Login
{% endblock %}

{% block content %}

        <section>
        <h1 style="clear:both">Create an account</h1>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <table>
                    {{ render_field(form.username, size=50) }}
                    {{ render_field(form.email, size=50) }}
                    {{ render_field(form.password, size=50) }}
                    {{ render_field(form.password2, size=50) }}
                    <tr class="submit">
                        <td></td>
                        <td><button type="submit">Submit</button></td>
                    </tr>
                </table>
            </form>
        </section>

{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/tag.html
{% extends "base.html" %}

{% block title %}
Thermos -- Bookmarks tagged {{ tag }}
{% endblock %}

{% block content %}
    <article>
        <header>
            <h1>Bookmarks for {{ tag}}</h1>

            {% if tag.bookmarks.count() > 0 %}
                {% with bookmarks=tag.bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                User has not submitted any bookmarks yet.
            {% endif %}
        </header>
    </article>
{% endblock %}

thermos/templates/user.html
{% extends "base.html" %}

{% block title %}
Thermos -- Bookmarks for user {{ user.username }}
{% endblock %}

{% block content %}
    <article>
        <header>
            <h1>Bookmarks for {{ user.username }}</h1>

            <!--<ul>-->
                <!--{% for bm in user.bookmarks %}-->
                    <!--<li>-->
                        <!--<a href="{{ bm.url }}">{{ bm.description }}</a>-->
                        <!--<span class="timestamp">Added at {{bm.date }}</span>-->
                    <!--</li>-->
                <!--{% else %}-->
                    <!--<li>This user has not added any bookmarks.</li>-->
                <!--{% endfor %}-->
            <!--</ul>-->
            {% if user.bookmarks.count() > 0 %}
                {% with bookmarks=user.bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                User has not submitted any bookmarks yet.
            {% endif %}
        </header>
    </article>
{% endblock %}